### ISSUE TITLE
Config Problems

### ISSUE THREAD

**Issue by Mindless-hue** [AzureDoom/Doom-Angel-Ring-Fabric#10]
Hi, I know this mod is mostly for your own use and I really appreciate you allow the public to use it. I tried to play with the config to change durability and damage and such, however every time I tried, the ring would stop working. Anything other than the default seemed not to work unless, as the other issue ticket says, it drops to 898 or below. I'm perfectly happy using your default config, but if it is possible to allow changes it would be nice. I'm using it in 1.20.1. Hope its not too much of an ask.

**Comment by AzureDoom** [comment]
1.20.1 is no longer updated, I maintain only the latest MC version of this mod (at this time 1.21.1). If it happens there, please let me know.
