### ISSUE TITLE
1.17 Recipe does not function

### ISSUE THREAD

**Issue by TyreanDK** [AzureDoom/Doom-Angel-Ring-Fabric#2]
Using the recipe does not produce an item, I think the issue might be the actual recipe as it is listed as
"doomangelring:itemdoomangelring"

But in game it is listed as

 "doomangelring:angelring"

**Comment by AzureDoom** [comment]
Fixed in b379c10da621a72cc3d735f6d5f0a9370ea15aec update pending CF approval.
