### ISSUE TITLE
Flying can't be turned off when equiped with the angelring

### ISSUE THREAD

**Issue by PinkLasagna03** [AzureDoom/Doom-Angel-Ring-Fabric#6]
In version "Angel-Ring-Fabric-1.20.1-2.0.7" when you have equiped the angelring, you can't turn flying off. You can't press double space to go out of flying mode and you can't walk normally. Can you fix this?

**Comment by AzureDoom** [comment]
This is intended on how I coded it.

**Comment by PinkLasagna03** [comment]
> This is intended on how I coded it.

Can't you make this optional trough the config file? It feels kinda out of place when comparing to older versions of the mod and other angelring mods. I mean, it is kinda a hassle to manually take off the ring everytime when you want to go out of flight mode

**Comment by AzureDoom** [comment]
No, this is how I wanted it to work my flight mode as this is maintained for my uses first and for most.

**Comment by PinkLasagna03** [comment]
> No, this is how I wanted it to work my flight mode as this is maintained for my uses first and for most.

Okay thanks, then I know enough
