### ISSUE TITLE
1.20.2-1.20.4 update?

### ISSUE THREAD

**Issue by backanda** [AzureDoom/Doom-Angel-Ring-Fabric#8]
as the title says, any thoughts on keeping the mod updated to 1.20.2-1.20.4 and beyond?

**Comment by AzureDoom** [comment]
1.20.4 is planned but I have not had free time to update it yet.

**Comment by AzureDoom** [comment]
So for this, I just ended up doing 1.20.6, which is released now for Fabric and NeoForge!
