### ISSUE TITLE
Rings above 898 durability do not allow flight on 

### ISSUE THREAD

**Issue by Gray2743** [AzureDoom/Doom-Angel-Ring-Fabric#9]
Versions:
Minecraft 1.20.1
Fabric: 0.15.11
Mod Version: 3.0.1

Title is self explanatory. Undamaged and 899 durability angel rings do not allow the user to fly at all. 

The only remedy is to fall for a sufficient time to tick the damage on the ring by two. Then the flight kicks in and stops your falling.

This is also a problem for mending on rings. If you collect enough xp to fully repair the ring you will fall to your **doom**.

Don't know if it is intentional to have the ring take damage while falling either. Seems like it *should* be impossible to freely fall with the ring on but as stated, you can and must for at least 40 ticks by default for the ring to work.

This is a problem for those that want to change the config so it lasts basically forever. You have to change the config after its taken two ticks. Not horrible but still annoying.

**Comment by AzureDoom** [comment]
What mc version are you testing on?

**Comment by Gray2743** [comment]
> What mc version are you testing on?

Minecraft 1.20.1
Fabric: 0.15.11
Mod Version: 3.0.1

Sorry, hit post preemptively.

**Comment by AzureDoom** [comment]
1.20.1 is no longer maintained, please let me know if this happens on 1.21.1 at this time.
